using Microsoft.EntityFrameworkCore;
using MobileBill.Application.Billing;
using MobileBill.Application.Common;
using MobileBill.Application.Pdf;
using MobileBill.Domain.Entities;
using MobileBill.Domain.Enums;
using MobileBill.Infrastructure.Persistence;

namespace MobileBill.Infrastructure.Billing;
public sealed class EfBillBatchService(MobileBillDbContext db, IBillFileStorage storage, IPdfBillParser parser, ICurrentUserService user, IClock clock, IBillReviewAuthorizationService authorization) : IBillBatchService
{
    public async Task<PagedResult<BillBatchListItemDto>> ListAsync(BillBatchListRequest request, CancellationToken token)
    {
        var query = db.BillBatches.AsNoTracking().AsQueryable();
        if (request.Status is not null) query = query.Where(x => x.Status == request.Status);
        if (request.BillingYear is not null) query = query.Where(x => x.BillingYear == request.BillingYear);
        if (request.BillingMonth is not null) query = query.Where(x => x.BillingMonth == request.BillingMonth);
        if (request.ProviderId is not null) query = query.Where(x => x.ProviderId == request.ProviderId);
        var search = request.Search?.Trim();
        if (!string.IsNullOrWhiteSpace(search))
            query = query.Where(x => x.CorporateCode.Contains(search) || (x.OriginalFileName != null && x.OriginalFileName.Contains(search)) || x.Provider.Name.Contains(search));

        query = OrderBatches(query, request.SortBy, request.SortDirection);
        var total = await query.CountAsync(token);
        var items = await query.Skip((request.NormalizedPage - 1) * request.NormalizedPageSize).Take(request.NormalizedPageSize)
            .Select(x => new BillBatchListItemDto(x.Id, x.ProviderId, x.Provider.Name, x.CorporateCode, x.BillingYear, x.BillingMonth, x.CalculatedGrandTotal, x.ValidationLevel, x.Status, x.OriginalFileName, x.UploadedBy, x.UploadedAt))
            .ToListAsync(token);
        return new PagedResult<BillBatchListItemDto>(items, request.NormalizedPage, request.NormalizedPageSize, total);
    }

    public async Task<BillBatchDto> CreateAsync(CreateBillBatchRequest request, CancellationToken token)
    { if (!await authorization.AuthorizeAsync(BillWorkflowAction.PrepareBatch, token)) throw new BillReviewForbiddenException();
      if (request.BillingMonth is < 1 or > 12 || request.BillingYear < 2000 || string.IsNullOrWhiteSpace(request.CorporateCode)) throw new BillBatchValidationException("Provider, corporate code, and a valid billing period are required.");
      if (!await db.TelecomProviders.AnyAsync(x=>x.Id==request.ProviderId && x.IsActive,token)) throw new BillBatchValidationException("An active telecom provider is required.");
      var batch=new BillBatch { ProviderId=request.ProviderId, CorporateCode=request.CorporateCode.Trim(), BillingYear=request.BillingYear, BillingMonth=request.BillingMonth, CreatedAtUtc=clock.UtcNow, CreatedBy=user.UserId }; db.BillBatches.Add(batch); await db.SaveChangesAsync(token); return Map(batch); }
    public async Task<BillBatchDto> UploadAsync(Guid id, Stream content, string name, string? type, long length, CancellationToken token)
    { if (!await authorization.AuthorizeAsync(BillWorkflowAction.PrepareBatch, token)) throw new BillReviewForbiddenException();
      var batch=await Find(id,token); Require(batch.Status==BillBatchStatus.Draft,"Only Draft batches can be uploaded."); var staged=await storage.StageAsync(content,name,type,length,token); if(await db.BillBatches.AnyAsync(x=>x.FileHash==staged.FileHash,token)){await storage.DeleteAsync(staged.TemporaryPath,token);throw new BillBatchConflictException("This PDF content was already uploaded.");}
      try { batch.FileHash=staged.FileHash; batch.OriginalFileName=Path.GetFileName(name); batch.UploadedBy=user.DisplayName; batch.UploadedAt=clock.UtcNow; batch.Status=BillBatchStatus.Uploaded; batch.UpdatedBy=user.UserId; batch.UpdatedAtUtc=clock.UtcNow; await db.SaveChangesAsync(token); string? finalizedPath=null; try { finalizedPath=await storage.FinalizeAsync(staged,batch.Id,token); batch.StoredFilePath=finalizedPath; await db.SaveChangesAsync(token); } catch { if(finalizedPath is not null) await storage.DeleteAsync(finalizedPath,token); batch.FileHash=null;batch.OriginalFileName=null;batch.StoredFilePath=null;batch.UploadedBy=null;batch.UploadedAt=null;batch.Status=BillBatchStatus.Draft;await db.SaveChangesAsync(token); throw; } return Map(batch); }
      catch(DbUpdateException){await storage.DeleteAsync(staged.TemporaryPath,token);throw new BillBatchConflictException("This PDF content was already uploaded.");} }
    public async Task<BillBatchDto> ParseAsync(Guid id,CancellationToken token)
    { await RequirePrepareBatchAsync(token); var batch=await Find(id,token);Require(batch.Status==BillBatchStatus.Uploaded && batch.StoredFilePath is not null,"Only Uploaded batches can be parsed."); var storedFilePath=batch.StoredFilePath!; try { await using var file=await storage.OpenReadAsync(storedFilePath,token); var result=await parser.ParseAsync(file,token); await using var tx=await db.Database.BeginTransactionAsync(token); var lines=result.Lines.Select(x=>new BillLine { BillBatchId=batch.Id, MobileNumber=x.MobileAccountNumber, PageNumber=x.PageNumber, RawText=x.RawExtractedText, ExtractionStatus=x.ExtractionStatus==PdfBillLineExtractionStatus.Success?BillLineExtractionStatus.Extracted:BillLineExtractionStatus.ValidationFailed, ExtractionError=x.ExtractionError, PreviousDueAmount=x.PreviousDueAmount, Payments=x.Payments, TotalUsageCharges=x.TotalUsageCharges, Idd=x.IDD, Roaming=x.Roaming, ValueAddedServices=x.VAS, Discounts=x.Discounts, BillAdjustmentsBalanceTransfers=x.BillAdjustments, CommitmentCharges=x.CommitmentCharges, LatePaymentCharges=x.LatePaymentCharges, AddToBill=x.AddToBill, InstalmentPlans=x.InstalmentPlans, GovernmentTaxesAndLevies=x.GovernmentTaxesLevies, Vat=x.VAT, ChargesForBillPeriod=x.ChargesForBillPeriod, TotalDueAmount=x.TotalDueAmount, CreatedAtUtc=clock.UtcNow, CreatedBy=user.UserId }).ToList(); db.BillLines.AddRange(lines); batch.CalculatedGrandTotal=lines.Where(x=>x.ExtractionStatus==BillLineExtractionStatus.Extracted).Sum(x=>x.TotalDueAmount); batch.StatedGrandTotal=result.StatedGrandTotal;batch.Difference=result.StatedGrandTotal is null?null:result.StatedGrandTotal-batch.CalculatedGrandTotal;batch.GrandTotalSource=result.GrandTotalSource;batch.Status=BillBatchStatus.Parsed;await db.SaveChangesAsync(token);await tx.CommitAsync(token);return Map(batch,result.TotalAccounts,result.SuccessfulAccounts,result.FailedAccounts,result.Warnings); } catch(BillBatchValidationException){throw;} catch(Exception ex){throw new BillBatchParsingException("PDF parsing failed; the batch remains Uploaded.",ex);} }
    public async Task<BillBatchDto> ValidateAsync(Guid id,CancellationToken token)
    { await RequirePrepareBatchAsync(token); var b=await Find(id,token);Require(b.Status is BillBatchStatus.Parsed or BillBatchStatus.ValidationFailed,"Only Parsed batches can be validated.");var lines=await db.BillLines.Where(x=>x.BillBatchId==id).ToListAsync(token);b.CalculatedGrandTotal=lines.Where(x=>x.ExtractionStatus==BillLineExtractionStatus.Extracted).Sum(x=>x.TotalDueAmount);var failed=lines.Any(x=>x.ExtractionStatus!=BillLineExtractionStatus.Extracted);b.Difference=b.StatedGrandTotal is null?null:b.StatedGrandTotal-b.CalculatedGrandTotal;if(failed){b.Status=BillBatchStatus.ValidationFailed;b.ValidationLevel=ValidationLevel.None;b.ValidationWarning="One or more PDF account candidates failed structural parsing.";}else if(b.StatedGrandTotal is null){b.Status=BillBatchStatus.Validated;b.ValidationLevel=ValidationLevel.StructuralOnly;b.ValidationWarning="Source PDF grand total could not be independently extracted. Account rows passed structural parsing checks, but the total was derived from parsed lines.";}else if(b.Difference==0m){b.Status=BillBatchStatus.Validated;b.ValidationLevel=ValidationLevel.IndependentTotal;b.ValidationWarning=null;}else{b.Status=BillBatchStatus.ValidationFailed;b.ValidationLevel=ValidationLevel.None;b.ValidationWarning="The independent source total does not match the calculated account total.";}b.ValidatedBy=user.DisplayName;b.ValidatedAt=clock.UtcNow;await db.SaveChangesAsync(token);return Map(b,lines.Count,lines.Count(x=>x.ExtractionStatus==BillLineExtractionStatus.Extracted),lines.Count(x=>x.ExtractionStatus!=BillLineExtractionStatus.Extracted),DurableWarnings(b,lines)); }
    public async Task<BillBatchDto> GetAsync(Guid id,CancellationToken token){var batch=await Find(id,token);var lines=await db.BillLines.AsNoTracking().Where(x=>x.BillBatchId==id).ToListAsync(token);return Map(batch,lines.Count,lines.Count(x=>x.ExtractionStatus==BillLineExtractionStatus.Extracted),lines.Count(x=>x.ExtractionStatus!=BillLineExtractionStatus.Extracted),DurableWarnings(batch,lines));}
    public async Task<PagedResult<BillLineDto>> GetLinesAsync(Guid id,PagedRequest request,CancellationToken token){_ = await Find(id,token);var q=db.BillLines.AsNoTracking().Where(x=>x.BillBatchId==id);var search=request.Search?.Trim();if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.MobileNumber.Contains(search));var ordered=q.OrderBy(x=>x.PageNumber).ThenBy(x=>x.MobileNumber);var total=await ordered.CountAsync(token);var items=await ordered.Skip((request.NormalizedPageNumber-1)*request.NormalizedPageSize).Take(request.NormalizedPageSize).Select(x=>Map(x)).ToListAsync(token);return new(items,request.NormalizedPageNumber,request.NormalizedPageSize,total);}
    private async Task RequirePrepareBatchAsync(CancellationToken token)
    {
        if (!await authorization.AuthorizeAsync(BillWorkflowAction.PrepareBatch, token)) throw new BillReviewForbiddenException();
    }
    private async Task<BillBatch> Find(Guid id,CancellationToken token)
    {
        var batch = await db.BillBatches.SingleOrDefaultAsync(x => x.Id == id, token)
            ?? throw new BillBatchNotFoundException(id);
        await db.Entry(batch).Reference(x => x.Provider).LoadAsync(token);
        return batch;
    }
    private static IQueryable<BillBatch> OrderBatches(IQueryable<BillBatch> query,string? sortBy,string? direction){var descending=string.Equals(direction,"desc",StringComparison.OrdinalIgnoreCase);return sortBy?.Trim().ToLowerInvariant() switch{"billingyear"=>descending?query.OrderByDescending(x=>x.BillingYear).ThenByDescending(x=>x.BillingMonth):query.OrderBy(x=>x.BillingYear).ThenBy(x=>x.BillingMonth),"billingmonth"=>descending?query.OrderByDescending(x=>x.BillingMonth).ThenByDescending(x=>x.BillingYear):query.OrderBy(x=>x.BillingMonth).ThenBy(x=>x.BillingYear),"provider"=>descending?query.OrderByDescending(x=>x.Provider.Name):query.OrderBy(x=>x.Provider.Name),"corporatecode"=>descending?query.OrderByDescending(x=>x.CorporateCode):query.OrderBy(x=>x.CorporateCode),"calculatedgrandtotal"=>descending?query.OrderByDescending(x=>x.CalculatedGrandTotal):query.OrderBy(x=>x.CalculatedGrandTotal),"status"=>descending?query.OrderByDescending(x=>x.Status):query.OrderBy(x=>x.Status),"uploadedat"=>descending?query.OrderByDescending(x=>x.UploadedAt):query.OrderBy(x=>x.UploadedAt),_=>query.OrderByDescending(x=>x.BillingYear).ThenByDescending(x=>x.BillingMonth).ThenByDescending(x=>x.UploadedAt)};}
    private static IReadOnlyList<string> DurableWarnings(BillBatch batch,IEnumerable<BillLine> lines){var warnings=new List<string>();if(!string.IsNullOrWhiteSpace(batch.ValidationWarning))warnings.Add(batch.ValidationWarning);warnings.AddRange(lines.Where(x=>x.ExtractionStatus!=BillLineExtractionStatus.Extracted&&!string.IsNullOrWhiteSpace(x.ExtractionError)).Select(x=>$"{x.MobileNumber}: {x.ExtractionError}").Distinct());return warnings;}
    private static void Require(bool c,string m){if(!c)throw new BillBatchConflictException(m);} private static BillBatchDto Map(BillBatch b,int totalCandidates=0,int successfulCount=0,int failedCount=0,IReadOnlyList<string>? warnings=null)=>new(b.Id,b.ProviderId,b.CorporateCode,b.BillingYear,b.BillingMonth,b.Status,b.OriginalFileName,b.FileHash,b.UploadedBy,b.UploadedAt,b.StatedGrandTotal,b.CalculatedGrandTotal,b.Difference,b.GrandTotalSource,b.ValidationLevel,b.ValidationWarning,b.Provider?.Name,totalCandidates,successfulCount,failedCount,warnings??[]); private static BillLineDto Map(BillLine x)=>new(x.Id,x.MobileNumber,x.PageNumber,x.ExtractionStatus,x.ExtractionError,x.PreviousDueAmount,x.Payments,x.TotalUsageCharges,x.Idd,x.Roaming,x.ValueAddedServices,x.Discounts,x.BillAdjustmentsBalanceTransfers,x.CommitmentCharges,x.LatePaymentCharges,x.AddToBill,x.InstalmentPlans,x.GovernmentTaxesAndLevies,x.Vat,x.ChargesForBillPeriod,x.TotalDueAmount,x.RawText);
}
